# Generated by Django 5.1.7 on 2025-09-23 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('cover_file', models.FileField(blank=True, null=True, upload_to='cover_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('edit_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('resume_image', models.ImageField(blank=True, null=True, upload_to='resume_images/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('edit_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
