from django.contrib import admin
from django.urls import path

from Employee import views
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from Employee.views import manage_ip_restriction

urlpatterns = [
    path('',crm_admin_login,name = 'crm_admin_login'),
    path('login/',crm_admin_login,name = 'crm_admin_login'),
    path('404/',user_not_found_view,name = 'user_not_found_view'),
    path('ip-restriction/', manage_ip_restriction, name='manage_ip_restriction'),
    path('admin-logout/', crm_admin_logout, name='crm_admin_logout'),
    path('crm-dashboard/',crm_dashboard,name = 'crm_dashboard'),
    path('admin-candidate-registration/',admin_candidate_registration,name = 'admin_candidate_registration'),
    path('check-mobile-number-crm/',check_mobile_number_duplicate,name = 'check_mobile_number_duplicate'),
    path('candidate-list/',admin_candidate_list,name = 'admin_candidate_list'),
    path('candidate-details/<int:id>/', admin_candidate_profile, name='admin_candidate_profile'),
    path('candidate/<int:candidate_id>/<str:model_type>/delete/', delete_candidate, name='delete_candidate'),
    path('admin-company-list/',admin_company_list,name = 'admin_company_list'),
    path('admin-company-registration/',admin_company_registration,name = 'admin_company_registration'),
    path('admin-company-profile/<int:id>/', admin_company_profile, name='admin_company_profile'),
    path('admin-vendor-list/',admin_vendor_list,name = 'admin_vendor_list'),
    path('evms-candidate-list/',admin_evms_candidate_list,name = 'admin_evms_candidate_list'),
    path('vendor-candidate-list/<int:id>/',admin_vendor_candidate_list,name = 'admin_vendor_candidate_list'),
    path('evms-candidate-profile/<int:id>/',evms_candidate_profile,name = 'evms_candidate_profile'),
    path('evms-vendor-profile/<int:id>/',admin_vendor_profile,name = 'admin_vendor_profile'),
    path('vendor-pay-list/',admin_evms_vendor_paylist, name = 'admin_evms_vendor_paylist'),
    path('vendor-transaction-history/',admin_evms_vendor_transaction_history, name = 'admin_evms_vendor_transaction_history'),
    path('export-vendors/', admin_export_vendors_to_excel, name='admin_export_vendors_to_excel'),
    path('selected-candidate-list/', selected_candidate, name='selected_candidate'),
    path('follow-up-candidate/',follow_up_candidate, name = 'follow_up_candidate'),
    path('leads/',generated_leads, name = 'generated_leads'),
    path('admin-vacancy-list/',admin_vacancy_list,name = 'admin_vacancy_list'),
    path('admin-profile/<int:id>/', crm_admin_profile, name='crm_admin_profile'),
    path('candidates/bulk-upload/', admin_candidate_bulk_upload, name='admin_candidate_bulk_upload'),
    path('candidate/<int:candidate_id>/chats/', admin_candidate_chat_list, name='admin_candidate_chat_list'),
    path('candidate/chats/<int:pk>/delete/', admin_delete_chat, name='admin_delete_chat'),
    path('candidate/<int:candidate_id>/interviews/', admin_interview_list, name='admin_interview_list'),
    path('interview/<int:interview_id>/', admin_interview_detail, name='admin_interview_detail'),
    path('interview/<int:interview_id>/delete/', admin_delete_interview, name='admin_delete_interview'),
    path('company/<int:company_id>/communications/', admin_company_communication_list, name='admin_company_communication_list'),
    path('communication/<int:communication_id>/', admin_company_communication_detail, name='admin_company_communication_detail'),
    path('communication/<int:communication_id>/delete/', admin_delete_company_communication, name='admin_delete_company_communication'),
    path('company/<int:company_id>/contacts/', admin_company_contacts_list, name='admin_company_contacts_list'),
    path('company/<int:company_id>/contacts/add/', admin_company_contacts_list, name='admin_company_contact_create'),
    path('contacts/<int:contact_id>/', admin_company_contact_detail, name='admin_company_contact_detail'),
    path('contacts/<int:contact_id>/delete/', admin_delete_company_contact, name='admin_delete_company_contact'),
    path('download-candidates/', download_candidate_details, name='download_candidates'),
    path('vendor/bank-details/<str:vendor_code>/', vendor_bank_details, name='vendor_bank_details'),
    path('vendor/process-payment/<str:vendor_code>/', process_payment, name='process_payment'),
    path('evms-candidate-list/',admin_evms_candidate_list,name = 'admin_evms_candidate_list'),
    path('evms-candidate-profile/<int:id>/',evms_candidate_profile,name = 'evms_candidate_profile'),
    path('evms-candidate-chat-list/<int:candidate_id>/',admin_evms_candidate_chat_list,name = 'admin_evms_candidate_chat_list'),
    path('evms-candidate-chat-list/<int:pk>/delete/',admin_evms_delete_chat,name = 'admin_evms_delete_chat'),
    path('evms-candidate-interview-list/<int:candidate_id>/',admin_evms_interview_list,name = 'admin_evms_interview_list'),
    path('evms-candidate-interview-detail/<int:interview_id>/',admin_evms_interview_detail,name = 'admin_evms_interview_detail'),
    path('evms-candidate-interview-detail/<int:interview_id>/delete/',admin_evms_delete_interview,name = 'admin_evms_delete_interview'),
    path('admin-invoice-list/',admin_invoice_list,name = 'admin_invoice_list'),
    path('admin-invoice-detail/<int:candidate_id>/', generate_candidate_invoice, name='generate_candidate_invoice'),
    path('admin-company-selected-candidates/<int:company_id>/', selected_candidate_in_company, name='selected_candidate_in_company'),
    path('bulk-candidate-invoice-generate/<int:company_id>/', bulk_candidate_invoice_generate, name='bulk_candidate_invoice_generate'),
    path('admin-invoice-bulk-generate/<int:company_id>/', generate_bulk_candidate_invoice, name='generate_bulk_candidate_invoice'),
    path('candidate-assignment/', admin_assign_candidate, name='admin_assign_candidate'),
    path('crm-dashboard/employee/<str:employee_name>/<str:filter_type>/', employee_candidates_list, name='employee_candidates_list'),
    path('admin-employee-calls/', admin_calls_list, name='admin_calls_list'),
    path('ajax/get-employee-candidates/', get_employee_candidates, name='get_employee_candidates'),
    path('ajax/get-filtered-activity-list/',get_filtered_activity_list, name='get_filtered_activity_list'),
    path('api/get-candidates/', get_candidates_api, name='get_candidates_api'),
    path('admin/tasks/', admin_task_dashboard, name='admin_task_dashboard'),
    path('tasks/<int:pk>/', admin_task_detail_and_reassign, name='admin_task_detail_and_reassign'),
    path('bulk-assign/', bulk_assign_candidates_api, name='bulk_assign_candidates_api'),
    path('emta/job-applications/', emta_co_in_job_application_view, name='emta_co_in_job_application_view'),
    path('emta/course-inquiries/', emta_co_in_course_application_view, name='emta_co_in_course_application_view'),
    path('emta/contact-queries/', emta_co_in_contact_queries_view, name='emta_co_in_contact_queries_view'),
    path('banking-counselling/', banking_counselling_view, name='manage_banking_counselling'),
    path('admin-bfsi-candidate-registration/',admin_bfsi_candidate_registration,name = 'admin_bfsi_candidate_registration'),
    path('check-mobile-number-bfsi/',check_mobile_number_duplicate_bfsi,name = 'check_mobile_number_duplicate_bfsi'),
    path('interview-schedule/', interview_schedule_list, name='interview_schedule_list'),
    path('notifications/read/<int:notification_id>/', mark_notification_as_read, name='mark_notification_as_read'),
    path('notifications/read-all/', mark_all_as_read, name='mark_all_as_read'),
    path('notifications/history/', notification_history, name='notification_history'),
    path('api/notifications/unread/', get_unread_notifications_api, name='api_unread_notifications'),
    path('employee-daily-report/', employee_daily_report, name='employee_daily_report'),
    path('ajax/get-daily-activities/', get_daily_activities_ajax, name='get_daily_activities_ajax'),


    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)