# Generated by Django 5.1.5 on 2025-01-27 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('Contact', models.CharField(default='No', max_length=10)),
                ('resume', models.FileField(upload_to='candidate/resume/')),
                ('sector', models.CharField(max_length=50)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('totalCommission', models.CharField(default='0', max_length=100)),
                ('Contact_by', models.CharField(default='None', max_length=50)),
                ('Remark', models.CharField(max_length=200)),
                ('commission_Generate_date', models.CharField(default=0, max_length=20)),
                ('Payment_Status', models.CharField(default='Pending', max_length=30)),
                ('Job_Type', models.CharField(max_length=30)),
                ('Payment_complete_date', models.CharField(max_length=20)),
                ('authentication_status', models.CharField(max_length=20)),
                ('submission_time', models.DateTimeField()),
                ('candidate_image', models.ImageField(blank=True, null=True, upload_to='candidate_images/')),
                ('unique_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('refer_code', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.TextField(max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('profileVerification', models.CharField(default='Under Process', max_length=50)),
                ('total_commission_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_profile_image', models.ImageField(blank=True, null=True, upload_to='Vendor_profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_document', models.FileField(upload_to='Bank/')),
                ('account_type', models.CharField(max_length=100)),
                ('preffered_payout_date', models.CharField(max_length=10)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('ifs_code', models.CharField(max_length=20)),
                ('micr_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVMS.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_bussiness_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('Gumasta_number', models.CharField(max_length=15)),
                ('gumasta_image', models.FileField(upload_to='Gumasata/')),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_image', models.FileField(upload_to='GST/')),
                ('Bpan_number', models.CharField(max_length=15)),
                ('Bpan_image', models.FileField(upload_to='Bussiness pan card/')),
                ('MSME_number', models.CharField(max_length=15)),
                ('MSME_image', models.FileField(upload_to='MSME/')),
                ('Contact_number', models.CharField(max_length=12)),
                ('Bphoto_outer', models.FileField(upload_to='Bussiness photo/outer')),
                ('Bphoto_inside', models.FileField(upload_to='Bussiness photo/inside')),
                ('Busness_email', models.EmailField(max_length=50)),
                ('VCname', models.CharField(max_length=50)),
                ('VCmobile', models.CharField(max_length=12)),
                ('VCaddress', models.CharField(max_length=150)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVMS.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_profile_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('adhar_card_number', models.CharField(max_length=15)),
                ('pan_card_number', models.CharField(max_length=15)),
                ('adhar_card_image', models.FileField(upload_to='adhar/')),
                ('pan_card_image', models.FileField(upload_to='pan/')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVMS.vendor')),
            ],
        ),
    ]
