# Generated by Django 5.1.7 on 2025-05-02 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('candidate_alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('candidate_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('lead_source', models.CharField(blank=True, default='EVMS', max_length=255, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_location', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('diploma', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_year', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_month', models.CharField(blank=True, max_length=255, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('current_working_status', models.CharField(blank=True, max_length=50, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=10, null=True)),
                ('call_connection', models.CharField(blank=True, max_length=255, null=True)),
                ('calling_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_generate', models.CharField(blank=True, max_length=255, null=True)),
                ('send_for_interview', models.CharField(blank=True, max_length=255, null=True)),
                ('next_follow_up_date', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_photo', models.FileField(blank=True, null=True, upload_to='candidate-photo/')),
                ('candidate_resume', models.FileField(blank=True, null=True, upload_to='candidate-resume/')),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('submit_by', models.CharField(blank=True, max_length=100, null=True)),
                ('selection_status', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=10, null=True)),
                ('offered_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('candidate_joining_date', models.CharField(blank=True, max_length=255, null=True)),
                ('emta_commission', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_date', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('vendor_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor_payout_date', models.DateField(blank=True, default=None, null=True)),
                ('vendor_commission_status', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_generation_date', models.DateField(blank=True, default=None, null=True)),
                ('vendor_payment_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_status', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_done_by', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_done_by_date', models.DateField(blank=True, null=True)),
                ('submit_recipt', models.FileField(blank=True, null=True, upload_to='vendor-payout-recipt/')),
            ],
        ),
        migrations.CreateModel(
            name='Referal_poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_image', models.FileField(blank=True, null=True, upload_to='referal_poster/')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('refer_code', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.TextField(blank=True, max_length=10, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('profileVerification', models.CharField(default='Under Process', max_length=50)),
                ('total_commission_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_profile_image', models.ImageField(blank=True, null=True, upload_to='Vendor_profile_image/')),
                ('qr_code_plain', models.ImageField(blank=True, null=True, upload_to='qr_codes_plain/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EVMS.candidate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='EVMS.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor_bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_document', models.FileField(upload_to='Bank/')),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preffered_payout_date', models.CharField(blank=True, max_length=10, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifs_code', models.CharField(blank=True, max_length=20, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVMS.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_bussiness_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=266, null=True)),
                ('busness_type', models.CharField(blank=True, max_length=100, null=True)),
                ('Gumasta_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gumasta_image', models.FileField(blank=True, null=True, upload_to='Gumasata/')),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_image', models.FileField(blank=True, null=True, upload_to='GST/')),
                ('Bpan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Bpan_image', models.FileField(blank=True, null=True, upload_to='Bussiness pan card/')),
                ('MSME_number', models.CharField(blank=True, max_length=15, null=True)),
                ('MSME_image', models.FileField(blank=True, null=True, upload_to='MSME/')),
                ('Contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('Bphoto_outer', models.FileField(blank=True, null=True, upload_to='Bussiness photo/outer')),
                ('Bphoto_inside', models.FileField(blank=True, null=True, upload_to='Bussiness photo/inside')),
                ('Busness_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('VCname', models.CharField(blank=True, max_length=50, null=True)),
                ('VCmobile', models.CharField(blank=True, max_length=12, null=True)),
                ('VCaddress', models.CharField(blank=True, max_length=150, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVMS.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_profile_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('adhar_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('adhar_card_image', models.FileField(blank=True, null=True, upload_to='adhar/')),
                ('pan_card_image', models.FileField(blank=True, null=True, upload_to='pan/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVMS.vendor')),
            ],
        ),
    ]
