# Generated by Django 5.1.7 on 2025-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='other_call_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_interview_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_lead_generate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_lead_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_origin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_selection_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_working_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='selection_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
