# Generated by Django 5.0.2 on 2025-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_profile_details',
            name='location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
