# Generated by Django 5.1.7 on 2025-07-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='other_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
