# Generated by Django 5.1.7 on 2025-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0002_candidate_other_call_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_salary_type',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary_type',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
