# Generated by Django 5.0.2 on 2025-01-30 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0002_vendor_profile_details_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='location',
            new_name='current_working_status',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='submit_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Contact_by',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Job_Type',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Payment_Status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Payment_complete_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Remark',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='authentication_status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_image',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='commission_Generate_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='submission_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='totalCommission',
        ),
        migrations.AddField(
            model_name='candidate',
            name='call_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='calling_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_alternate_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_joining_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_mobile_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_photo',
            field=models.FileField(default=0, upload_to='candidate-photo/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_resume',
            field=models.FileField(default=0, upload_to='candidate-resume/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='company_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='diploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='emta_commission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lead_generate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='lead_source',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='next_follow_up_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='offered_salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='origin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='payout_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='register_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='selection_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='selection_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='send_for_interview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='unique_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
