# Generated by Django 5.1.7 on 2025-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0002_candidate_other_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='joining_status',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
    ]
