# Generated by Django 5.1.7 on 2025-09-18 07:34

import EVMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0003_alter_candidate_joining_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('position_of_interest', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position of Interest')),
                ('previous_experience', models.TextField(verbose_name='Previous Work Experience')),
                ('resume', models.FileField(blank=True, null=True, upload_to=EVMS.models.resume_upload_path)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Portfolio URL')),
                ('interview_availability', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
