# Generated by Django 5.1.7 on 2025-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0003_candidate_current_salary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_bussiness_details',
            name='shop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor_bussiness_details',
            name='shop_other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor_bussiness_details',
            name='shop_pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile_details',
            name='other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor_profile_details',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
