# Generated by Django 5.0.2 on 2025-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0003_rename_location_candidate_current_working_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lead_source',
            field=models.CharField(default='EVMS', max_length=255),
        ),
    ]
