# Generated by Django 5.0.2 on 2025-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0004_alter_candidate_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vendor_commission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vendor_commission_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vendor_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
