# Generated by Django 5.1.7 on 2025-09-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0004_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='email',
            new_name='candidate_email',
        ),
    ]
