# Generated by Django 5.1.7 on 2025-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0004_vendor_bussiness_details_shop_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='vendor_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
