# Generated by Django 5.1.7 on 2025-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0005_rename_email_jobapplication_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='candidate_email',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
