# Generated by Django 5.1.7 on 2025-06-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0005_alter_candidate_vendor_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='vendor_commission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
