# Generated by Django 5.0.2 on 2025-03-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0005_candidate_vendor_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='vendor_payout_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
