# Generated by Django 5.1.7 on 2025-06-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0006_alter_candidate_vendor_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='verification_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
