# Generated by Django 5.1.7 on 2025-09-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0007_courseinquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseInquiry',
        ),
    ]
