# Generated by Django 5.1.7 on 2025-06-16 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_candidate_interview_alert_shown'),
        ('EVMS', '0007_vendor_verification_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_date', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.TextField()),
                ('employee_name', models.CharField(max_length=255)),
                ('chat_type', models.CharField(choices=[('internal', 'Internal Note'), ('candidate', 'Candidate Communication'), ('client', 'Client Communication')], default='internal', max_length=20)),
                ('is_important', models.BooleanField(default=False)),
                ('next_followup', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='EVMS.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evms_candidate_chat_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evms_candidate_chat_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Chat',
                'verbose_name_plural': 'Candidate Chats',
                'ordering': ['-chat_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate_Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=255)),
                ('interviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interviewer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('interviewer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='scheduled', max_length=20)),
                ('interview_mode', models.CharField(choices=[('in_person', 'In-Person'), ('phone', 'Phone'), ('video', 'Video Call'), ('online_test', 'Online Test'), ('assessment', 'Assessment'), ('group_discussion', 'Group Discussion'), ('walk_in', 'Walk-In'), ('campus', 'Campus'), ('telephonic', 'Telephonic'), ('virtual', 'Virtual'), ('face_to_face', 'Face-to-Face'), ('on_site', 'On Site'), ('other', 'Other')], default='in_person', max_length=20)),
                ('location', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Rating out of 10', null=True)),
                ('is_technical', models.BooleanField(default=False)),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('requirements', models.TextField(blank=True, help_text='Any special requirements', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='interview_docs/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='EVMS.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evms_candidate_interview_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evms_candidate_interview_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Interview',
                'verbose_name_plural': 'Candidate Interviews',
                'ordering': ['-interview_date', '-interview_time'],
            },
        ),
        migrations.CreateModel(
            name='CandidateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField(default=dict)),
                ('remark', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='EVMS.candidate')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evms_candidate_activities', to='App.employee')),
            ],
            options={
                'verbose_name_plural': 'Candidate Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
