# Generated by Django 5.1.7 on 2025-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0008_delete_courseinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course_interest', models.CharField(choices=[('Sales Officer', 'Sales Officer Training Program'), ('Relationship Manager', 'Relationship Manager Training Program'), ('Credit Officer', 'Credit Officer Training Program'), ('Operations Training', 'Operations Training Program')], max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Course Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
