# Generated by Django 5.1.7 on 2025-06-16 06:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_candidate_interview_alert_shown'),
        ('EVMS', '0008_candidate_chat_candidate_interview_candidateactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate_chat',
            new_name='EVMS_Candidate_chat',
        ),
        migrations.RenameModel(
            old_name='Candidate_Interview',
            new_name='EVMS_Candidate_Interview',
        ),
        migrations.RenameModel(
            old_name='CandidateActivity',
            new_name='EVMS_CandidateActivity',
        ),
    ]
