# Generated by Django 5.1.7 on 2025-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0010_candidate_created_at_candidate_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='employee_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
