# Generated by Django 5.1.7 on 2025-11-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0010_contactquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
