# Generated by Django 5.1.7 on 2025-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0011_alter_candidate_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
