# Generated by Django 5.0.2 on 2025-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0011_alter_vendor_bank_details_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='date_of_birth',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Bpan_image',
            field=models.FileField(blank=True, null=True, upload_to='Bussiness pan card/'),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Bpan_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Bphoto_inside',
            field=models.FileField(blank=True, null=True, upload_to='Bussiness photo/inside'),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Bphoto_outer',
            field=models.FileField(blank=True, null=True, upload_to='Bussiness photo/outer'),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Busness_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Contact_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='Gumasta_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='MSME_image',
            field=models.FileField(blank=True, null=True, upload_to='MSME/'),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='MSME_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='VCaddress',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='VCmobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='VCname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='gst_image',
            field=models.FileField(blank=True, null=True, upload_to='GST/'),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='gumasta_image',
            field=models.FileField(blank=True, null=True, upload_to='Gumasata/'),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='shop_address',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_bussiness_details',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='adhar_card_image',
            field=models.FileField(blank=True, null=True, upload_to='adhar/'),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='adhar_card_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='pan_card_image',
            field=models.FileField(blank=True, null=True, upload_to='pan/'),
        ),
        migrations.AlterField(
            model_name='vendor_profile_details',
            name='pan_card_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
