# Generated by Django 5.1.7 on 2025-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0012_alter_candidate_next_follow_up_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='next_follow_up_date',
        ),
        migrations.AddField(
            model_name='candidate',
            name='next_follow_up_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
