# Generated by Django 5.0.2 on 2025-03-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0013_alter_candidate_candidate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vendor_payment_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
