# Generated by Django 5.1.7 on 2025-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0014_candidate_vendor_payment_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='refer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
