# Generated by Django 5.1.7 on 2025-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0014_alter_evms_candidate_interview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='invoice_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='invoice_attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoice_attachments/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='invoice_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evms_candidate_interview',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Pending', 'Pending'), ('In Process', 'In Process'), ('Failed', 'Failed')], default='scheduled', max_length=20),
        ),
    ]
