# Generated by Django 5.1.7 on 2025-04-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0015_alter_candidate_refer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='qr_code_plain',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes_plain/'),
        ),
    ]
