# Generated by Django 5.1.7 on 2025-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0015_candidate_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
