# Generated by Django 5.1.7 on 2025-06-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0016_candidate_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='invoice_paid_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
