# Generated by Django 5.1.7 on 2025-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0017_candidate_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='preferred_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
