# Generated by Django 5.1.7 on 2025-07-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0018_candidate_preferred_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='employee_assigned',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
