# Generated by Django 5.1.7 on 2025-04-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0018_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal_poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_image', models.FileField(blank=True, null=True, upload_to='referal_poster/')),
            ],
        ),
    ]
