# Generated by Django 5.1.7 on 2025-04-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVMS', '0019_referal_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='admin_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
