# Generated by Django 5.1.7 on 2025-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
