# Generated by Django 5.1.7 on 2025-05-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancydetails',
            name='flat_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetails',
            name='pay_per_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetails',
            name='percentage_of_ctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
