# Generated by Django 5.1.7 on 2025-07-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_registration',
            name='attech_proposal',
            field=models.FileField(blank=True, null=True, upload_to='Company-Proposals/'),
        ),
    ]
