# Generated by Django 5.0.2 on 2025-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesession',
            name='logout_reason',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
