# Generated by Django 5.1.7 on 2025-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('hidden', 'Hidden'), ('ese_hi', 'Ese Hi')], default='private', max_length=10),
        ),
    ]
