# Generated by Django 5.1.7 on 2025-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='current_salary_type',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_registration',
            name='current_working_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_registration',
            name='expected_salary_type',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
