# Generated by Django 5.1.7 on 2025-04-29 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_announcement_created_at_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_registration_created', to='App.employee'),
        ),
        migrations.AlterField(
            model_name='candidate_registration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_registration_updated', to='App.employee'),
        ),
    ]
