# Generated by Django 5.1.7 on 2025-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_designation_color_designation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_chat',
            name='attachment',
            field=models.FileField(blank=True, default=0, upload_to='chat_attachments/'),
            preserve_default=False,
        ),
    ]
