# Generated by Django 5.1.7 on 2025-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_candidate_registration_current_salary_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancydetails',
            name='replacement_criteria_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
