# Generated by Django 5.1.7 on 2025-05-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_document_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate_registration',
            old_name='current_salary_type',
            new_name='current_salary_type1',
        ),
    ]
