# Generated by Django 5.1.7 on 2025-05-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_current_salary_type_candidate_registration_current_salary_type1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate_registration',
            old_name='current_salary_type1',
            new_name='current_salary_type',
        ),
    ]
