# Generated by Django 5.0.2 on 2025-02-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_announcement_announcement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement_image',
            new_name='announcements_image',
        ),
    ]
