# Generated by Django 5.1.7 on 2025-04-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_candidate_chat_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_chat',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='candidate_chat',
            name='chat_type',
        ),
        migrations.RemoveField(
            model_name='candidate_chat',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='candidate_chat',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='candidate_chat',
            name='next_followup',
        ),
    ]
