# Generated by Django 5.1.7 on 2025-04-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_candidate_registration_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
