# Generated by Django 5.1.7 on 2025-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_vacancydetails_batch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='other_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_preferred_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
