# Generated by Django 5.1.7 on 2025-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_vacancydetails_replacement_criteria_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='selection_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
