# Generated by Django 5.1.7 on 2025-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_candidate_chat_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_chat',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='candidate_chat',
            name='chat_type',
            field=models.CharField(choices=[('internal', 'Internal Note'), ('candidate', 'Candidate Communication'), ('client', 'Client Communication')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate_chat',
            name='employee_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate_chat',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate_chat',
            name='next_followup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
