# Generated by Django 5.1.7 on 2025-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_salary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents_details',
            name='other_document_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
