# Generated by Django 5.1.7 on 2025-05-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_ticket_ticket_attachment_ticket_ticket_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
