# Generated by Django 5.1.7 on 2025-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_registration_other_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Registration', 'verbose_name_plural': 'Candidate Registrations'},
        ),
        migrations.AlterField(
            model_name='candidate_registration',
            name='unique_code',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
    ]
