# Generated by Django 5.0.2 on 2025-02-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_announcement_image_announcement_announcements_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesocialmedia',
            name='employee',
        ),
        migrations.RenameField(
            model_name='employeeadditionalinfo',
            old_name='designation',
            new_name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeadditionalinfo',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeadditionalinfo',
            name='reporting_to',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Documents_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=200)),
                ('expiry_date', models.DateField()),
                ('document_file', models.FileField(null=True, upload_to='Employee-Documents/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents_details', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Education_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(blank=True, max_length=200)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('education_certificate', models.FileField(null=True, upload_to='Education-Certificate/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('natinality', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_address', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('designation_name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('experience_certificate', models.FileField(null=True, upload_to='Experience-Certificate/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='App.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='App.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='EmployeeSocialMedia',
        ),
    ]
