# Generated by Django 5.1.7 on 2025-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_registration_selection_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='preferred_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
