# Generated by Django 5.1.7 on 2025-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_candidate_registration_preferred_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_interview',
            name='alert_shown',
            field=models.BooleanField(default=False),
        ),
    ]
