# Generated by Django 5.1.7 on 2025-04-18 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_candidate_chat_attachment_candidate_chat_chat_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_interview',
            options={'ordering': ['-interview_date', '-interview_time'], 'verbose_name': 'Candidate Interview', 'verbose_name_plural': 'Candidate Interviews'},
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='interview_docs/'),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='interview_mode',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('phone', 'Phone'), ('video', 'Video Call'), ('online_test', 'Online Test')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='interviewer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='interviewer_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='interviewer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='is_technical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='job_position',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating out of 10', null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='requirements',
            field=models.TextField(blank=True, help_text='Any special requirements', null=True),
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate_interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='App.candidate_registration'),
        ),
        migrations.AlterField(
            model_name='candidate_interview',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_interview',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='scheduled', max_length=20),
        ),
    ]
