# Generated by Django 5.1.7 on 2025-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_candidate_registration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='hello_world',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
