# Generated by Django 5.0.2 on 2025-02-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_documents_details_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_address',
            old_name='natinality',
            new_name='nationality',
        ),
    ]
