# Generated by Django 5.1.7 on 2025-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_candidate_interview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_interview',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
