# Generated by Django 5.1.7 on 2025-07-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_candidate_registration_hello_world'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_registration',
            name='hello_world',
        ),
    ]
