# Generated by Django 5.1.7 on 2025-06-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_candidate_interview_alert_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_interview',
            name='alert_shown',
        ),
    ]
