# Generated by Django 5.1.7 on 2025-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_candidate_registration_hello_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_interview',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Duration in minutes', null=True),
        ),
    ]
