# Generated by Django 5.1.7 on 2025-04-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_candidate_interview_interviewer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('communication_date', models.DateTimeField()),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('message', 'Message'), ('video_call', 'Video Call'), ('letter', 'Letter'), ('proposal', 'Proposal')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('communication_details', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='App.company_registration')),
            ],
            options={
                'verbose_name': 'Company Communication',
                'verbose_name_plural': 'Company Communications',
                'ordering': ['-communication_date'],
            },
        ),
    ]
