# Generated by Django 5.0.2 on 2025-02-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_natinality_employee_address_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents_details',
            name='document_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
