# Generated by Django 5.1.7 on 2025-05-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_ticketactivity_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.employee'),
        ),
    ]
