# Generated by Django 5.1.7 on 2025-08-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_candidate_interview_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancydetails',
            name='experience_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='job_description_attachment',
            field=models.FileField(blank=True, null=True, upload_to='job_profile_attachments/'),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='job_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='job_profile_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='lingual_proficiency_specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='no_of_workingdays',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='process_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='shift_timing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancydetails',
            name='times_of_interview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
