# Generated by Django 5.1.7 on 2025-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_candidate_registration_next_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_interview',
            options={'ordering': ['-interview_date_time'], 'verbose_name': 'Candidate Interview', 'verbose_name_plural': 'Candidate Interviews'},
        ),
        migrations.RemoveField(
            model_name='candidate_interview',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='candidate_interview',
            name='interview_time',
        ),
        migrations.AddField(
            model_name='candidate_interview',
            name='interview_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
