# Generated by Django 5.0.2 on 2025-02-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_documents_details_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_details',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_details', to='App.employee'),
        ),
    ]
