# Generated by Django 5.1.7 on 2025-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_vacancydetails_experience_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_registration',
            options={},
        ),
        migrations.AlterField(
            model_name='candidateactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('call_update', 'Call Update'), ('status_changed', 'Status Changed')], max_length=20),
        ),
    ]
