# Generated by Django 5.1.7 on 2025-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_candidateactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='other_call_connection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_interview_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_lead_generate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_lead_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_selection_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='other_working_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
