# Generated by Django 5.1.7 on 2025-05-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_candidateactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_registration',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='candidate_registration',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='candidateactivity',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.employee'),
        ),
    ]
