# Generated by Django 5.0.2 on 2025-02-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_education_details_education_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents_details',
            name='expiry_date',
        ),
    ]
