# Generated by Django 5.1.7 on 2025-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_candidate_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate_registration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate Registration', 'verbose_name_plural': 'Candidate Registrations'},
        ),
        migrations.AlterField(
            model_name='candidateactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed')], max_length=20),
        ),
    ]
