# Generated by Django 5.1.7 on 2025-05-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_candidate_registration_other_call_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='joining_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
