# Generated by Django 5.0.2 on 2025-02-12 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_documents_details_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_details',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='App.employee'),
        ),
    ]
