# Generated by Django 5.1.7 on 2025-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_company_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_registration',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company_registration',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company_registration',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='company_invoice',
        ),
    ]
