# Generated by Django 5.1.7 on 2025-08-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_candidate_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='candidate_photo',
            field=models.FileField(blank=True, null=True, upload_to='candidate-photo/'),
        ),
        migrations.AlterField(
            model_name='candidate_registration',
            name='candidate_resume',
            field=models.FileField(blank=True, null=True, upload_to='candidate-resume/'),
        ),
        migrations.AlterField(
            model_name='candidateactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('call_made', 'Call Made'), ('status_changed', 'Status Changed'), ('interview_updated', 'Interview Updated'), ('interview_deleted', 'Interview Deleted'), ('invoice_updated', 'Invoice Updated')], max_length=50),
        ),
    ]
