# Generated by Django 5.1.7 on 2025-05-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_candidate_registration_joining_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='joining_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
