# Generated by Django 5.1.7 on 2025-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_candidate_registration_candidate_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_ips',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses (e.g., 192.168.1.1, 127.0.0.1).'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ip_restriction_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable IP Restriction'),
        ),
    ]
