# Generated by Django 5.1.7 on 2025-06-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_company_registration_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
