# Generated by Django 5.1.7 on 2025-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_candidate_registration_joining_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='other_origin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
