# Generated by Django 5.0.2 on 2025-02-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_education_details_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience_details',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='App.employee'),
        ),
    ]
