# Generated by Django 5.1.7 on 2025-09-01 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_employee_allowed_ips_employee_ip_restriction_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to='App.employee', verbose_name='Assigned Employee'),
        ),
    ]
