# Generated by Django 5.1.7 on 2025-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_company_registration_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_registration',
            name='company_status',
        ),
        migrations.AddField(
            model_name='company_registration',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
