# Generated by Django 5.1.7 on 2025-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_candidate_registration_other_origin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='current_salary_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='expected_salary_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
