# Generated by Django 5.1.7 on 2025-09-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_onboardingemployee_onboardingemergencycontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo_id', 'Photo ID (Aadhar/PAN)'), ('address_proof', 'Address Proof'), ('photograph', 'Passport Size Photograph'), ('resume', 'Resume/CV'), ('offer_letter', 'Signed Offer Letter')], max_length=50)),
                ('document_file', models.FileField(upload_to='employee-onboarding-documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='App.onboardingemployee')),
            ],
        ),
    ]
