# Generated by Django 5.1.7 on 2025-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_company_registration_company_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='invoice_paid_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
