# Generated by Django 5.0.2 on 2025-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_family_details_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='experience_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_registration',
            name='experience_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
