# Generated by Django 5.1.7 on 2025-05-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_companyactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
