# Generated by Django 5.1.7 on 2025-09-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_employeesessionip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSessionIP',
        ),
    ]
