# Generated by Django 5.1.7 on 2025-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_candidate_registration_next_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
