# Generated by Django 5.0.2 on 2025-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_candidate_registration_experience_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
