# Generated by Django 5.1.7 on 2025-05-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_candidate_registration_next_follow_up_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_registration',
            old_name='employee_name',
            new_name='handled_by',
        ),
        migrations.AddField(
            model_name='company_registration',
            name='opened_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
