# Generated by Django 5.0.2 on 2025-02-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_candidate_registration_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesession',
            old_name='login_time',
            new_name='punch_in_time',
        ),
        migrations.RenameField(
            model_name='employeesession',
            old_name='logout_reason',
            new_name='punch_out_reason',
        ),
        migrations.RenameField(
            model_name='employeesession',
            old_name='logout_time',
            new_name='punch_out_time',
        ),
    ]
