# Generated by Django 5.1.7 on 2025-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_rename_employee_name_company_registration_handled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_interview',
            name='interview_mode',
            field=models.CharField(choices=[('in_person', 'In-Person'), ('phone', 'Phone'), ('video', 'Video Call'), ('online_test', 'Online Test'), ('assessment', 'Assessment'), ('group_discussion', 'Group Discussion'), ('walk_in', 'Walk-In'), ('campus', 'Campus'), ('telephonic', 'Telephonic'), ('virtual', 'Virtual'), ('face_to_face', 'Face-to-Face'), ('on_site', 'On Site'), ('other', 'Other')], default='in_person', max_length=20),
        ),
    ]
