# Generated by Django 5.0.2 on 2025-02-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_rename_login_time_employeesession_punch_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('ticket_name', models.CharField(max_length=255)),
                ('ticket_description', models.TextField(blank=True, null=True)),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('ticket_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('ticket_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_created_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_closed_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_remark', models.TextField(blank=True, null=True)),
                ('ticket_assign_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='App.employee')),
                ('ticket_assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='App.employee')),
            ],
        ),
    ]
