# Generated by Django 5.0.2 on 2025-03-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='selection_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
