# Generated by Django 5.0.2 on 2025-03-27 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_candidate_registration_selection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='next_follow_up_date',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Candidate_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_date', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.TextField()),
                ('chat_by', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.candidate_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.CharField(max_length=255)),
                ('interview_time', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.candidate_registration')),
            ],
        ),
    ]
