# Generated by Django 5.1.7 on 2025-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='bfsi_batch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='bfsi_candidature_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='bfsi_payment_attachment',
            field=models.FileField(blank=True, null=True, upload_to='bfsi_payment_attachments/'),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='bfsi_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='bfsi_payment_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate_registration',
            name='bfsi_payment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
