# Generated by Django 5.0.2 on 2025-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_candidate_registration_next_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
