# Generated by Django 5.0.2 on 2025-03-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_candidate_registration_next_follow_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
