# Generated by Django 5.1.7 on 2025-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_candidate_registration_bfsi_batch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='admin_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
