# Generated by Django 5.1.7 on 2025-10-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_candidate_registration_admin_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('call_made', 'Call Made'), ('status_changed', 'Status Changed'), ('interview_updated', 'Interview Updated'), ('interview_deleted', 'Interview Deleted'), ('invoice_updated', 'Invoice Updated'), ('viewed', 'Viewed')], max_length=50),
        ),
    ]
