# Generated by Django 5.0.2 on 2025-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_candidate_registration_candidate_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_registration',
            name='vacancy_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='vacancy_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
