# Generated by Django 5.1.7 on 2025-10-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_candidateactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='lead_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
