# Generated by Django 5.0.2 on 2025-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_company_registration_vacancy_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_registration',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
