# Generated by Django 5.1.7 on 2025-04-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_candidate_registration_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeexpense',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
