# Generated by Django 5.1.7 on 2025-10-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('selection', 'Selection'), ('interview', 'Interview'), ('follow_up', 'Follow Up'), ('joining_date', 'Joining Date'), ('admin_remark', 'Admin Remark'), ('default', 'Default')], default='default', max_length=20),
        ),
    ]
