# Generated by Django 5.1.7 on 2025-04-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_officeexpense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_registration',
            name='company_usp',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='company_vacancy_unique_code',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='fresher_status',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='job_opening_origin',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='job_profile',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='maximum_experience',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='maximum_salary_range',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='minimum_education_qualification',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='minimum_experience',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='minimum_salary_range',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='replacement_criteria',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='sector_type',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='special_instruction',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='status_of_incentive',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='third_party_name',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='vacancy_closing_date',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='vacancy_opening_date',
        ),
        migrations.RemoveField(
            model_name='company_registration',
            name='vacancy_status',
        ),
        migrations.CreateModel(
            name='VacancyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.CharField(blank=True, max_length=255, null=True)),
                ('company_vacancy_unique_code', models.CharField(max_length=15)),
                ('vacancy_opening_date', models.DateField(blank=True, null=True)),
                ('vacancy_status', models.CharField(max_length=10)),
                ('payroll', models.CharField(blank=True, max_length=255, null=True)),
                ('third_party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_opening_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_type', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fresher_status', models.CharField(max_length=50)),
                ('minimum_age', models.CharField(blank=True, max_length=10, null=True)),
                ('maximum_age', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_education_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('minimum_salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_salary_range', models.CharField(blank=True, max_length=255, null=True)),
                ('vacancy_closing_date', models.DateField(blank=True, null=True)),
                ('special_instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('company_usp', models.CharField(blank=True, max_length=255, null=True)),
                ('status_of_incentive', models.CharField(blank=True, max_length=255, null=True)),
                ('replacement_criteria', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='App.company_registration')),
            ],
        ),
    ]
