# Generated by Django 5.1.7 on 2025-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_remove_company_registration_company_usp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_registration',
            name='company_contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='Company-Logo/'),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='company_unique_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='interview_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_registration',
            name='status_of_proposal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetails',
            name='fresher_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancydetails',
            name='vacancy_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
