# Generated by Django 5.1.7 on 2025-04-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_termination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
