# Generated by Django 5.1.7 on 2025-10-28 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_notification_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The actual time of the punch event.')),
                ('punch_type', models.CharField(choices=[('IN', 'Punch In'), ('OUT', 'Punch Out')], max_length=3)),
                ('reason', models.TextField(blank=True, help_text='Reason for punching out (e.g., end of day, break) or for a correction.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_punches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='App_attenda_user_id_0e4b28_idx')],
            },
        ),
    ]
