# Generated by Django 5.1.7 on 2025-10-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_attendancepunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_registration',
            name='expected_joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
