# Generated by Django 5.1.7 on 2025-11-03 09:45

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_candidate_registration_expected_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('account_type', models.CharField(choices=[('hostinger', 'Hostinger'), ('gmail', 'Gmail'), ('other', 'Other (IMAP/SMTP)')], default='hostinger', max_length=20)),
                ('email_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Password for Hostinger/Other (encrypted).', null=True)),
                ('gmail_credentials', models.TextField(blank=True, help_text='JSON credentials blob for Gmail OAuth 2.0', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='App.employee')),
            ],
        ),
    ]
