# Generated by Django 5.1.7 on 2025-11-04 12:13

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_employeeemailaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeemailaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='employeeemailaccount',
            name='gmail_credentials',
        ),
        migrations.AlterField(
            model_name='employeeemailaccount',
            name='email_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Password for the email account (encrypted).', null=True),
        ),
    ]
